version: "3.8"
services:
  view_service:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    depends_on:
      - view_mongodb
    networks:
      - shared_network

  view_mongodb:
    image: mongo:latest
    container_name: view_mongodb
    ports:
      - "27019:27017"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
