version: "3.8"
services:
  view_service:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    depends_on:
      - mongodb_view
    networks:
      - shared_network

  mongodb_view:
    image: mongo:latest
    container_name: mongodb_view
    ports:
      - "27019:27017"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
